set_property SRC_FILE_INFO {cfile:C:/Users/usnam/Documents/GitHub/SPRO4/uart/uart.srcs/constrs_1/new/uart_constraints.xdc rfile:../../../uart.srcs/constrs_1/new/uart_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports user_reset]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y11 [get_ports tx_top]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11 [get_ports rx_top]
